# Generated by Django 5.0.4 on 2024-04-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alumni_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
