# Generated by Django 5.0.4 on 2024-04-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_user_alumni_id_delete_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
