# Generated by Django 5.0.4 on 2024-05-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_remove_friendrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
