# Generated by Django 5.0.4 on 2024-04-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_remove_alumni_id_alumni_name_alter_alumni_alumni_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='alumni',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni'),
        ),
    ]
