# Generated by Django 5.0.4 on 2024-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_group_is_active_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Video')]),
        ),
    ]
