# Generated by Django 5.0.4 on 2024-05-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_media', to='alumni.invitation'),
        ),
        migrations.AlterField(
            model_name='media',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='alumni.post'),
        ),
    ]
