# Generated by Django 5.0.4 on 2024-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_media_invitation_alter_media_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='recipients_groups',
            field=models.ManyToManyField(related_name='recipients_groups', to='alumni.group'),
        ),
    ]
