# Generated by Django 5.0.4 on 2024-05-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_post_allow_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('post', 'user', 'type')},
        ),
    ]
