# Generated by Django 5.0.4 on 2024-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_remove_user_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='Đây là caption mới', max_length=100),
            preserve_default=False,
        ),
    ]
